# Generated by Django 4.0.4 on 2022-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_remove_agency_zone_zone_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='zones.agency'),
        ),
    ]
