# Generated by Django 4.0.4 on 2022-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_alter_zone_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zone',
            new_name='agency',
        ),
    ]
