# Generated by Django 4.0.4 on 2022-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_alter_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='common_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
