# Generated by Django 4.0.4 on 2022-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0007_alter_agency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='zone',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
