# Generated by Django 4.0.4 on 2022-05-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0008_technician_alter_zone_options_zone_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='zones.technician'),
        ),
    ]
