# Generated by Django 4.0.4 on 2022-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0009_zone_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
